import type { Crop, Pesticide } from "./types";

export const crops: Crop[] = [
  { name: "Wheat", n_rate: 120, p_rate: 60, k_rate: 30, irrigation: 450, yield: 5.5 },
  { name: "Maize", n_rate: 150, p_rate: 70, k_rate: 40, irrigation: 500, yield: 7.0 },
  { name: "Soybean", n_rate: 20, p_rate: 50, k_rate: 30, irrigation: 400, yield: 2.5 },
  { name: "Sunflower", n_rate: 60, p_rate: 40, k_rate: 40, irrigation: 380, yield: 2.2 },
  { name: "Potato", n_rate: 180, p_rate: 90, k_rate: 100, irrigation: 600, yield: 30.0 },
  { name: "Rice", n_rate: 160, p_rate: 70, k_rate: 60, irrigation: 1200, yield: 6.5 },
  { name: "Barley", n_rate: 100, p_rate: 50, k_rate: 30, irrigation: 400, yield: 4.5 },
  { name: "Rapeseed", n_rate: 160, p_rate: 70, k_rate: 50, irrigation: 450, yield: 3.0 },
  { name: "Sugar beet", n_rate: 180, p_rate: 80, k_rate: 90, irrigation: 550, yield: 60.0 },
  { name: "Vegetables", n_rate: 120, p_rate: 80, k_rate: 70, irrigation: 500, yield: 25.0 },
  { name: "Oats", n_rate: 90, p_rate: 45, k_rate: 25, irrigation: 360, yield: 3.8 },
  { name: "Rye", n_rate: 80, p_rate: 40, k_rate: 20, irrigation: 320, yield: 3.6 },
  { name: "Sorghum", n_rate: 110, p_rate: 50, k_rate: 35, irrigation: 340, yield: 5.2 },
  { name: "Millet", n_rate: 60, p_rate: 30, k_rate: 20, irrigation: 280, yield: 2.4 },
  { name: "Cotton", n_rate: 140, p_rate: 60, k_rate: 50, irrigation: 700, yield: 3.2 },
  { name: "Alfalfa", n_rate: 20, p_rate: 35, k_rate: 140, irrigation: 850, yield: 10.0 },
  { name: "Peas", n_rate: 25, p_rate: 40, k_rate: 30, irrigation: 300, yield: 2.8 },
  { name: "Lentils", n_rate: 20, p_rate: 35, k_rate: 25, irrigation: 260, yield: 1.8 },
  { name: "Chickpea", n_rate: 25, p_rate: 45, k_rate: 25, irrigation: 300, yield: 2.1 },
  { name: "Tomato", n_rate: 170, p_rate: 90, k_rate: 180, irrigation: 650, yield: 55.0 },
  { name: "Onion", n_rate: 130, p_rate: 70, k_rate: 120, irrigation: 600, yield: 40.0 },
  { name: "Grapes", n_rate: 60, p_rate: 35, k_rate: 70, irrigation: 500, yield: 12.0 },
  { name: "Quinoa", n_rate: 80, p_rate: 40, k_rate: 30, irrigation: 350, yield: 2.6 },
  { name: "Buckwheat", n_rate: 60, p_rate: 30, k_rate: 25, irrigation: 300, yield: 2.0 },
  { name: "Spelt", n_rate: 110, p_rate: 50, k_rate: 30, irrigation: 420, yield: 4.0 },
  { name: "Fava bean", n_rate: 35, p_rate: 45, k_rate: 30, irrigation: 320, yield: 3.0 },
  { name: "Mung bean", n_rate: 30, p_rate: 40, k_rate: 25, irrigation: 280, yield: 1.6 },
  { name: "Cabbage", n_rate: 160, p_rate: 80, k_rate: 160, irrigation: 600, yield: 45.0 },
  { name: "Carrot", n_rate: 120, p_rate: 60, k_rate: 150, irrigation: 520, yield: 40.0 },
  { name: "Pepper", n_rate: 140, p_rate: 70, k_rate: 160, irrigation: 620, yield: 30.0 },
  { name: "Strawberry", n_rate: 120, p_rate: 60, k_rate: 120, irrigation: 550, yield: 20.0 },
  { name: "Melon", n_rate: 90, p_rate: 45, k_rate: 110, irrigation: 500, yield: 28.0 },
  { name: "Basil", n_rate: 80, p_rate: 40, k_rate: 90, irrigation: 480, yield: 12.0 },
  { name: "Mint", n_rate: 70, p_rate: 35, k_rate: 80, irrigation: 460, yield: 10.0 },
  { name: "Apple", n_rate: 80, p_rate: 45, k_rate: 120, irrigation: 520, yield: 25.0 },
  { name: "Citrus", n_rate: 90, p_rate: 50, k_rate: 130, irrigation: 600, yield: 28.0 },
  { name: "Cucumber", n_rate: 120, p_rate: 60, k_rate: 140, irrigation: 540, yield: 35.0 },
  { name: "Lettuce", n_rate: 100, p_rate: 50, k_rate: 100, irrigation: 480, yield: 25.0 },
  { name: "Pumpkin", n_rate: 110, p_rate: 55, k_rate: 130, irrigation: 520, yield: 22.0 },
  { name: "Garlic", n_rate: 110, p_rate: 55, k_rate: 120, irrigation: 480, yield: 18.0 },
  { name: "Flax", n_rate: 70, p_rate: 40, k_rate: 30, irrigation: 300, yield: 2.1 },
  { name: "Clover", n_rate: 25, p_rate: 35, k_rate: 120, irrigation: 700, yield: 9.0 }
];

export const pesticides: Pesticide[] = [
  { trade_name: "Roundup", substance: "Glyphosate", type: "Herbicide", ef: 29.0 },
  { trade_name: "Atrazine", substance: "Atrazine", type: "Herbicide", ef: 25.0 },
  { trade_name: "Harness", substance: "Acetochlor", type: "Herbicide", ef: 27.0 },
  { trade_name: "Karate", substance: "Lambda-cyhalothrin", type: "Insecticide", ef: 55.0 },
  { trade_name: "Decis", substance: "Deltamethrin", type: "Insecticide", ef: 50.0 },
  { trade_name: "Ridomil Gold", substance: "Metalaxyl", type: "Fungicide", ef: 45.0 },
  { trade_name: "Bravo", substance: "Chlorothalonil", type: "Fungicide", ef: 30.0 },
  { trade_name: "Tilt", substance: "Propiconazole", type: "Fungicide", ef: 35.0 },
  { trade_name: "Amistar", substance: "Azoxystrobin", type: "Fungicide", ef: 38.0 },
  { trade_name: "Dithane", substance: "Mancozeb", type: "Fungicide", ef: 32.0 },
  { trade_name: "Kocide", substance: "Copper hydroxide", type: "Fungicide", ef: 34.0 },
  { trade_name: "Dual Gold", substance: "S-metolachlor", type: "Herbicide", ef: 28.0 },
  { trade_name: "Callisto", substance: "Mesotrione", type: "Herbicide", ef: 26.0 },
  { trade_name: "Banvel", substance: "Dicamba", type: "Herbicide", ef: 27.0 },
  { trade_name: "2,4-D", substance: "2,4-D", type: "Herbicide", ef: 24.0 },
  { trade_name: "Confidor", substance: "Imidacloprid", type: "Insecticide", ef: 52.0 },
  { trade_name: "Dursban", substance: "Chlorpyrifos", type: "Insecticide", ef: 54.0 },
  { trade_name: "Karate Zeon", substance: "Lambda-cyhalothrin", type: "Insecticide", ef: 55.0 },
  { trade_name: "Select", substance: "Clethodim", type: "Herbicide", ef: 26.0 },
  { trade_name: "Basagran", substance: "Bentazone", type: "Herbicide", ef: 25.0 },
  { trade_name: "Granstar", substance: "Tribenuron-methyl", type: "Herbicide", ef: 24.0 },
  { trade_name: "Prowl", substance: "Pendimethalin", type: "Herbicide", ef: 27.0 },
  { trade_name: "Lasso", substance: "Alachlor", type: "Herbicide", ef: 26.0 },
  { trade_name: "Stomp", substance: "Pendimethalin", type: "Herbicide", ef: 27.0 },
  { trade_name: "Sencor", substance: "Metribuzin", type: "Herbicide", ef: 25.0 },
  { trade_name: "Reglone", substance: "Diquat", type: "Herbicide", ef: 23.0 },
  { trade_name: "Betanal", substance: "Phenmedipham", type: "Herbicide", ef: 24.0 },
  { trade_name: "Fusilade", substance: "Fluazifop-P-butyl", type: "Herbicide", ef: 26.0 },
  { trade_name: "Targa", substance: "Quizalofop-P-ethyl", type: "Herbicide", ef: 26.0 },
  { trade_name: "Score", substance: "Difenoconazole", type: "Fungicide", ef: 36.0 },
  { trade_name: "Topaz", substance: "Penconazole", type: "Fungicide", ef: 34.0 },
  { trade_name: "Switch", substance: "Cyprodinil", type: "Fungicide", ef: 39.0 },
  { trade_name: "Signum", substance: "Boscalid", type: "Fungicide", ef: 40.0 },
  { trade_name: "Quadris", substance: "Azoxystrobin", type: "Fungicide", ef: 38.0 },
  { trade_name: "Falcon", substance: "Tebuconazole", type: "Fungicide", ef: 36.0 },
  { trade_name: "Rovral", substance: "Iprodione", type: "Fungicide", ef: 33.0 },
  { trade_name: "Copper Oxychloride", substance: "Copper oxychloride", type: "Fungicide", ef: 34.0 },
  { trade_name: "Karathane", substance: "Dinocap", type: "Fungicide", ef: 35.0 },
  { trade_name: "Actara", substance: "Thiamethoxam", type: "Insecticide", ef: 53.0 },
  { trade_name: "Mospilan", substance: "Acetamiprid", type: "Insecticide", ef: 52.0 },
  { trade_name: "Match", substance: "Lufenuron", type: "Insecticide", ef: 51.0 },
  { trade_name: "Coragen", substance: "Chlorantraniliprole", type: "Insecticide", ef: 54.0 },
  { trade_name: "Vertimec", substance: "Abamectin", type: "Insecticide", ef: 56.0 },
  { trade_name: "Fastac", substance: "Alpha-cypermethrin", type: "Insecticide", ef: 54.0 },
  { trade_name: "Engeo", substance: "Thiamethoxam + Lambda-cyhalothrin", type: "Insecticide", ef: 58.0 },
  { trade_name: "Decis Expert", substance: "Deltamethrin", type: "Insecticide", ef: 50.0 },
  { trade_name: "Biscaya", substance: "Thiacloprid", type: "Insecticide", ef: 52.0 },
  { trade_name: "Confidor Energy", substance: "Imidacloprid + Deltamethrin", type: "Insecticide", ef: 57.0 },
  { trade_name: "Moddus", substance: "Trinexapac-ethyl", type: "Growth regulator", ef: 20.0 },
  { trade_name: "Cerone", substance: "Ethephon", type: "Growth regulator", ef: 19.0 },
  { trade_name: "Ethephon Max", substance: "Ethephon", type: "Growth regulator", ef: 19.0 },
  { trade_name: "Paclobutrazol", substance: "Paclobutrazol", type: "Growth regulator", ef: 21.0 },
  { trade_name: "Boron Mix", substance: "Boron chelate", type: "Growth regulator", ef: 18.0 }
];
